scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Prometheus itself

  - job_name: 'dialogue_generation'
    static_configs:
      - targets: ['localhost:8000']  # Your Python application
